# Generated by Django 5.1.15 on 2026-05-27 04:15

import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('odds_at_placement', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', django_fsm.FSMField(db_index=True, default='pending', max_length=50)),
                ('payout', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('cashout_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Apuesta',
                'verbose_name_plural': 'Apuestas',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='CombinedBet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake', models.DecimalField(decimal_places=4, max_digits=18)),
                ('combined_odds', models.DecimalField(decimal_places=4, max_digits=18)),
                ('status', django_fsm.FSMField(db_index=True, default='pending', max_length=50)),
                ('payout', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Apuesta combinada',
                'verbose_name_plural': 'Apuestas combinadas',
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('programado', 'Programado'), ('en_vivo', 'En vivo'), ('finalizado', 'Finalizado'), ('suspendido', 'Suspendido'), ('anulado', 'Anulado')], db_index=True, default='programado', max_length=20)),
                ('result_home', models.IntegerField(blank=True, null=True)),
                ('result_away', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_type', models.CharField(choices=[('1X2', 'Resultado (1X2)'), ('over_under', 'Más/Menos goles'), ('btts', 'Ambos equipos anotan'), ('handicap_asiatico', 'Handicap asiático')], max_length=30)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('line', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
            },
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('odds', models.DecimalField(decimal_places=4, max_digits=10)),
                ('is_winner', models.BooleanField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Selección',
                'verbose_name_plural': 'Selecciones',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-trophy', max_length=50)),
            ],
            options={
                'verbose_name': 'Deporte',
                'verbose_name_plural': 'Deportes',
            },
        ),
    ]
