# Generated by Django 5.1.15 on 2026-05-27 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='combinedbet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combined_bets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='market',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='betting.event'),
        ),
        migrations.AddField(
            model_name='selection',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='betting.market'),
        ),
        migrations.AddField(
            model_name='combinedbet',
            name='selections',
            field=models.ManyToManyField(related_name='combined_bets', to='betting.selection'),
        ),
        migrations.AddField(
            model_name='bet',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='betting.selection'),
        ),
        migrations.AddField(
            model_name='event',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='betting.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='market',
            unique_together={('event', 'market_type', 'line')},
        ),
    ]
