# Generated by Django 5.1.15 on 2026-05-28 06:45

import django_fsm
from django.db import migrations, models
from django.utils import timezone


def generate_bet_ids(apps, schema_editor):
    Bet = apps.get_model('betting', 'Bet')
    db_alias = schema_editor.connection.alias
    year = timezone.now().year
    counter = 1
    for bet in Bet.objects.using(db_alias).filter(bet_id='').order_by('placed_at'):
        bet.bet_id = f'BET-{year}-{counter:06d}'
        bet.save(update_fields=['bet_id'])
        counter += 1


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_id',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='ID de apuesta'),
        ),
        migrations.RunPython(generate_bet_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='bet',
            name='bet_id',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='ID de apuesta'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('settling', 'Liquidando'), ('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada'), ('cashed_out', 'Cash-out'), ('settled', 'Liquidada')], db_index=True, default='pending', max_length=50),
        ),
    ]
