# Generated by Django 5.1.15 on 2026-05-28

from django.db import migrations, models
import django_fsm


def populate_combined_bet_ids(apps, schema_editor):
    CombinedBet = apps.get_model('betting', 'CombinedBet')
    qs = CombinedBet.objects.filter(bet_id='').order_by('placed_at')
    year = 2026
    last_num = 0
    for cb in qs:
        last_num += 1
        cb.bet_id = f'CMB-{year}-{last_num:06d}'
        cb.save(update_fields=['bet_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_add_bet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedbet',
            name='bet_id',
            field=models.CharField(blank=True, editable=False, max_length=30, verbose_name='ID de apuesta'),
        ),
        migrations.AlterField(
            model_name='combinedbet',
            name='status',
            field=django_fsm.FSMField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('settling', 'Liquidando'), ('won', 'Ganada'), ('lost', 'Perdida'), ('void', 'Anulada'), ('cashed_out', 'Cash-out'), ('settled', 'Liquidada')], db_index=True, default='pending', max_length=50),
        ),
        migrations.RunPython(populate_combined_bet_ids, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='combinedbet',
            name='bet_id',
            field=models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='ID de apuesta'),
        ),
    ]
