# Generated by Django 5.1.15 on 2026-05-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_combinedbet_bet_id_alter_combinedbet_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinedbet',
            name='cashout_amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
