# Generated by Django 5.1.15 on 2026-05-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('same_ip_multi_account', 'Misma IP, múltiples cuentas'), ('identical_bet_pattern', 'Patrón de apuestas idénticas'), ('deposit_cashout', 'Depósito inmediato + cash-out'), ('bonus_abuse', 'Abuso de bono')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(default=dict)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Actividad sospechosa',
                'verbose_name_plural': 'Actividades sospechosas',
                'ordering': ['-created_at'],
            },
        ),
    ]
