# Generated by Django 5.1.15 on 2026-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraud', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suspiciousactivity',
            old_name='description',
            new_name='reason',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='reviewed',
        ),
        migrations.RemoveField(
            model_name='suspiciousactivity',
            name='rule_type',
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='activity_type',
            field=models.CharField(choices=[('same_ip_multi_account', 'Misma IP, múltiples cuentas'), ('identical_bet_pattern', 'Patrón de apuestas idénticas'), ('deposit_cashout', 'Depósito inmediato + cash-out'), ('bonus_abuse', 'Abuso de bono'), ('opposite_bets_hedging', 'Apuestas opuestas o cobertura')], default='same_ip_multi_account', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='severity',
            field=models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='suspiciousactivity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisada'), ('dismissed', 'Descartada'), ('confirmed', 'Confirmada')], default='pending', max_length=20),
        ),
    ]
