# Generated by Django 5.1.15 on 2026-05-27 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('betting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('wallet_usuario', 'Wallet Usuario'), ('casa', 'Casa'), ('apuestas_pendientes', 'Apuestas Pendientes'), ('bonos', 'Bonos')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('direction', models.CharField(choices=[('DEBIT', 'Débito'), ('CREDIT', 'Crédito')], max_length=6)),
                ('transaction_id', models.UUIDField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='betting.bet')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada contable',
                'verbose_name_plural': 'Entradas contables',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['account_type', 'user', 'created_at'], name='wallet_ledg_account_175aef_idx'), models.Index(fields=['transaction_id'], name='wallet_ledg_transac_a947a0_idx')],
            },
        ),
    ]
