# Generated by Django 5.1.15 on 2026-05-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_combinedbet_bet_id_alter_combinedbet_status'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='combined_bet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='betting.combinedbet'),
        ),
    ]
