# Generated by Django 5.1.15 on 2026-05-28 20:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_ledgerentry_combined_bet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('rollover_multiplier', models.IntegerField(default=5)),
                ('wagered_amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bono de Usuario',
                'verbose_name_plural': 'Bonos de Usuario',
            },
        ),
    ]
