# Generated by Django 5.1.15 on 2026-05-27 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('hash', models.CharField(max_length=64)),
                ('previous_hash', models.CharField(max_length=64)),
                ('chain_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'ordering': ['created_at'],
            },
        ),
    ]
