# Generated by Django 5.1.15 on 2026-05-27

from django.db import migrations


TRIGGER_SQL = """
CREATE OR REPLACE RULE audit_log_no_update AS
  ON UPDATE TO audit_auditlog DO INSTEAD NOTHING;

CREATE OR REPLACE RULE audit_log_no_delete AS
  ON DELETE TO audit_auditlog DO INSTEAD NOTHING;
"""

REVERSE_SQL = """
DROP RULE IF EXISTS audit_log_no_update ON audit_auditlog;
DROP RULE IF EXISTS audit_log_no_delete ON audit_auditlog;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
    ]

    operations = [
        migrations.RunSQL(TRIGGER_SQL, REVERSE_SQL)
    ]
